name: Mirror to Tencent Code

on:
  push:
  delete:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: mirror-repository
        uses: spyoungtech/mirror-action@v0.4.3
        with:
         REMOTE: 'https://git.code.tencent.com/Tencent_Open_Source/ScriptX.git'
         GIT_USERNAME: ${{ secrets.TENCENT_CODE_GIT_USERNAME }}
         GIT_PASSWORD: ${{ secrets.TENCENT_CODE_GIT_PASSWORD }}
